# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install deps
        run: |
          npm install

      - name: Execute tests
        run: |
          npm run test

  # This workflow contains a single job called "build"
  arduino-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Build docker image
        run: docker build -t arduino-test .

      - name: Execute arduino-test
        run:  docker run -v ${{ github.workspace }}/arduino-test/build:/app/arduino-test/sketches arduino-test

      - name: Archive build artifact
        uses: actions/upload-artifact@master
        with:
          name: node-sketch-templater-build-artifact
          path: ${{ github.workspace }}/arduino-test/build

      - name: Download build artifact
        uses: actions/download-artifact@master
        with:
          name: node-sketch-templater-build-artifact
          path: ./
