name: Test compilation with development package

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  compile:
    name: Test compilation
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Cache node modules
        uses: actions/cache@v2.1.4
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: |
            ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Cache arduino-dir
        uses: actions/cache@v2.1.4
        env:
          cache-name: arduino-dir
        with:
          path: |
            ~/.arduino15
          key: ${{ runner.os }}-cache-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-cache-
            ${{ runner.os }}-

      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v1.1.1

      - name: Install test deps
        run: |
          npm ci
          arduino-cli --additional-urls "https://raw.githubusercontent.com/sensebox/senseBoxMCU-core/master/package_sensebox_index.json" core update-index
          arduino-cli --additional-urls "https://raw.githubusercontent.com/sensebox/senseBoxMCU-core/master/package_sensebox_index.json" core install sensebox:samd
          arduino-cli core install arduino:samd
          arduino-cli core install arduino:avr

      - name: Execute test suite
        run: |
          npm run test
          npm run arduino-test
